#!/usr/bin/env bash
set -x

if [ ! -f dist/ ]; then
  rm -rv dist/
fi

cabal clean
mkdir -pv dist/
bun run js
cp -v $(nix-build -A miso-lynx-examples-ghcjs9122)/bin/counter.jsexe/all.js out.js
chmod +rw out.js
bun build --minify-whitespace out.js --target=bun --outfile=all.js
file all.js
bun run bundle
http-server -c-1 dist
