#!/usr/bin/env bash
set -x

if [ ! -f dist/ ]; then
  rm -rv dist/
fi

cabal clean
mkdir -pv dist/
bun run js
cp -v $(nix-build -A miso-lynx-examples-ghcjs9122)/bin/counter.jsexe/all.js .
chmod +rw all.js
bun build --minify-whitespace all.js --target=bun --outfile=dist/all.js
file dist/all.js
bun run bundle
http-server dist
